### PR TITLE
Solution by Soma Zsoter (all 4 tasks)

### PR DESCRIPTION
**Pull request by somazsoter**
Hi there,

I solved all the tasks including the bonus one :)

Best, Soma

### CODE REVIEW

**Comment by career-at-melli** [comment]
Dear @somazsoter 
Congratulations 🎉 and thank you for participating. Cool, you where able to finish this challenge.
Please send our Recruiting Manager Leonie your contact details. So she can discuss the next steps with you.

**Comment by somazsoter** [comment]
Hello there @meetapKarriere, 
Thank you! Sure, could you please send me her email? Or alternatively this is my email: somazsoter@gmail.com

All the best, Soma

**Comment by career-at-melli** [comment]
Dear @somazsoter ,

thank you very much for your reply.
This is our email address: [karriere@melli.com](mailto:karriere@melli.com)

I talked to Hans, our CTO, he will have a look at your code. Could you send me your CV in the meantime?
I am looking forward to your reply.
Have a great day

**Comment by somazsoter** [comment]
Dear @meetapKarriere,

Great, thanks a lot, I just sent you an email. 
Have a nice day as well and looking forward to meeting you, Soma

**Pull request closed without merging**
